package az.test.exception;

public class NotInChaosException extends BaseException {

}
